# Generated by Django 2.2.6 on 2019-10-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191015_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
    ]
